/**
 * Permission Constants
 * Based on FRONTEND_API_DOCUMENTATION.md
 * Centralized definition of all permissions used in the application
 */

export const PERMISSIONS = {
  // Article Permissions
  ARTICLE_CREATE: 'PERMISSION_ARTICLE_CREATE',
  ARTICLE_READ: 'PERMISSION_ARTICLE_READ',
  ARTICLE_UPDATE: 'PERMISSION_ARTICLE_UPDATE',
  ARTICLE_DELETE: 'PERMISSION_ARTICLE_DELETE',
  ARTICLE_APPROVE: 'PERMISSION_ARTICLE_APPROVE',
  ARTICLE_SUMMARY: 'PERMISSION_ARTICLE_SUMMARY',
  ARTICLE_TTS: 'PERMISSION_ARTICLE_TTS',
  
  // User Permissions
  USER_CREATE: 'PERMISSION_USER_CREATE',
  USER_READ: 'PERMISSION_USER_READ',
  USER_UPDATE: 'PERMISSION_USER_UPDATE',
  USER_DELETE: 'PERMISSION_USER_DELETE',
  USER_ASSIGN_ROLE: 'PERMISSION_USER_ASSIGN_ROLE',
  
  // Role Permissions
  ROLE_CREATE: 'PERMISSION_ROLE_CREATE',
  ROLE_READ: 'PERMISSION_ROLE_READ',
  ROLE_UPDATE: 'PERMISSION_ROLE_UPDATE',
  ROLE_DELETE: 'PERMISSION_ROLE_DELETE',
  ROLE_ASSIGN_PERMISSION: 'PERMISSION_ROLE_ASSIGN_PERMISSION',
  
  // Category Permissions
  CATEGORY_CREATE: 'PERMISSION_CATEGORY_CREATE',
  CATEGORY_UPDATE: 'PERMISSION_CATEGORY_UPDATE',
  CATEGORY_DELETE: 'PERMISSION_CATEGORY_DELETE',
  
  // Other Permissions
  PERMISSION_READ: 'PERMISSION_PERMISSION_READ',
  STATS_READ: 'PERMISSION_STATS_READ'
};

/**
 * Role Constants
 */
export const ROLES = {
  USER: 'USER',
  AUTHOR: 'AUTHOR',
  MODERATOR: 'MODERATOR',
  ADMIN: 'ADMIN'
};

/**
 * Role to Permissions Mapping
 * Based on actual database permissions
 * Updated from user-provided permission list
 */
export const ROLE_PERMISSIONS = {
  [ROLES.USER]: [
    PERMISSIONS.ARTICLE_READ
  ],
  [ROLES.AUTHOR]: [
    PERMISSIONS.ARTICLE_CREATE,
    PERMISSIONS.ARTICLE_READ,
    PERMISSIONS.ARTICLE_UPDATE,
    PERMISSIONS.ARTICLE_DELETE,
    PERMISSIONS.ARTICLE_SUMMARY,
    PERMISSIONS.ARTICLE_TTS
    // NOTE: AUTHOR does NOT have ARTICLE_APPROVE
  ],
  [ROLES.MODERATOR]: [
    PERMISSIONS.ARTICLE_READ,
    PERMISSIONS.ARTICLE_UPDATE,
    PERMISSIONS.ARTICLE_APPROVE,
    PERMISSIONS.ARTICLE_DELETE,
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_UPDATE,
    PERMISSIONS.CATEGORY_DELETE,
    PERMISSIONS.STATS_READ
    // NOTE: MODERATOR does NOT have ARTICLE_CREATE, ARTICLE_SUMMARY, ARTICLE_TTS
  ],
  [ROLES.ADMIN]: [
    // All permissions
    ...Object.values(PERMISSIONS)
  ]
};

